### ISSUE TITLE
Some specific app’s barmoji and emojiport won’t work when enable Low-Level File Handles

### ISSUE THREAD

**Issue by nk950357** [jjolano/shadow#53] opened 2022-11-22 03:06 UTC
The app line's barmoji and emojiport won't work after enable the low-level file handler bypass option.
![image](https://user-images.githubusercontent.com/51433626/203211406-6ab961a1-e816-4d77-a588-71dd8005bc43.jpeg)![image](https://user-images.githubusercontent.com/51433626/203211413-7550553a-a361-43d9-a173-13283477f233.png)

This is my settings right now![image](https://user-images.githubusercontent.com/51433626/203211532-7e3ba16e-f8d1-45a4-82ac-e969a292b9b8.png)![image](https://user-images.githubusercontent.com/51433626/203211547-a15ed14d-78f5-4f03-ab6f-628e2af724c2.png)

**Comment by jjolano** [comment] 2022-11-22 03:32
Seems like a tweak compatibility issue. Try enabling Tweak Compatibility (Extra). Which tweaks exactly are used here?

**Comment by jjolano** [comment] 2022-11-22 05:08
I'll see what I can do. I also use EmojiPort with no issues with same jailbreak and iOS version.

**Comment by nk950357** [comment] 2022-11-22 05:46
Ok, thanks for big help!
Actually, only the line app appears this problem, other app with same
settings have no issue at all.

**Comment by jjolano** [comment] 2022-11-22 06:29
So, very odd thing is that I can replicate it with the same tweak configuration. However when I enable "AAAASnowBoardFontsSB" it works properly. When that tweak is disabled it gives me the same result as you've shown. I will still investigate further as it seems like it's related to the tweak compatibility system.

**Comment by nk950357** [comment] 2022-11-22 06:36
> plicate it with the same tweak configuration. However when I enable "AAAASnowBoardFontsSB" it works properly. When that tweak is disabled it gives me the same result as you've shown. I will still investigate further as it seems like it's related to the tweak compatibility system.

Unfortunally, I didn't find the "AAAASnowBoardFontsSB" in the libhooker. Does it mean i need to install snowboard first?
The way i install the emojiport isnt by snowboard, just with native emojiport with resources.

**Comment by jjolano** [comment] 2022-11-22 06:38
> > plicate it with the same tweak configuration. However when I enable "AAAASnowBoardFontsSB" it works properly. When that tweak is disabled it gives me the same result as you've shown. I will still investigate further as it seems like it's related to the tweak compatibility system.
> 
> Unfortunally, I didn't find the "AAAASnowBoardFontsSB" in the libhooker. Does it mean i need to install snowboard first? The way i install the emojiport isnt by snowboard, just with native emojiport with resources.

Yes, I'm using the EmojiFontManager which has an extension within SnowBoard.

**Comment by nk950357** [comment] 2022-11-22 06:41
> > > plicate it with the same tweak configuration. However when I enable "AAAASnowBoardFontsSB" it works properly. When that tweak is disabled it gives me the same result as you've shown. I will still investigate further as it seems like it's related to the tweak compatibility system.
> > 
> > 
> > Unfortunally, I didn't find the "AAAASnowBoardFontsSB" in the libhooker. Does it mean i need to install snowboard first? The way i install the emojiport isnt by snowboard, just with native emojiport with resources.
> 
> Yes, I'm using the EmojiFontManager which has an extension within SnowBoard.

I'll try snowboard way later. Don't know why native way has this problem.

**Comment by jjolano** [comment] 2022-11-22 06:44
I just tried with a debug build of Shadow, and I feel it's just the hook itself which causes the emoji to break for some reason. There are no restrictions being placed on any emoji file. Seems like it's just an unfortunate issue in this case. I would try the SnowBoard way and hopefully that's a good workaround.

**Comment by nk950357** [comment] 2022-11-22 14:11
> I just tried with a debug build of Shadow, and I feel it's just the hook itself which causes the emoji to break for some reason. There are no restrictions being placed on any emoji file. Seems like it's just an unfortunate issue in this case. I would try the SnowBoard way and hopefully that's a good workaround.

Sorry for not related question, but may i ask you where did you found the 15.4's emoji works on snowboard?
because i can't found the resources of 15.4 emoji for snowboard...

**Comment by jjolano** [comment] 2022-11-22 14:25
All from PoomSmart![image](https://user-images.githubusercontent.com/552925/203338848-23292d81-57c6-4b78-85f5-8bd165917083.png)

**Comment by nk950357** [comment] 2023-01-26 16:49
The newer emojiport doesn't support snowboard then the problem exist right now. Is there any new fix to fix it? Thanks

**Comment by jjolano** [comment] 2023-01-26 21:31
I don't seem to have any issues with the SnowBoard method. Which packages do you have specifically?

**Comment by jjolano** [comment] 2023-01-27 04:20
@nk950357 can you see if the issue occurs with the beta: 3.6.2-3? You will have to turn on the `Allow Tweak Resources` option.

**Comment by nk950357** [comment] 2023-01-29 04:34
> @nk950357 can you see if the issue occurs with the beta: 3.6.2-3? You will have to turn on the `Allow Tweak Resources` option.

Sorry for late replying. Unfortunately, still not work with latest beta and hookit framework.![image](https://user-images.githubusercontent.com/51433626/215305071-a51270e0-1d2e-4cba-9c43-a3cb2b1c1cb6.png)

**Comment by nk950357** [comment] 2023-01-29 04:36
> I don't seem to have any issues with the SnowBoard method. Which packages do you have specifically?
> 
> 
> 
> cc: @PoomSmart

Snowboard method works good, but the latest emojiport drops the support of snowboard.

**Comment by jjolano** [comment] 2023-01-29 05:41
Those instructions seem out of date. Maybe it comes from an old version of EmojiPort?

I have the latest packages of everything for EmojiPort and EFM, and all I have to do is enable EFM in SnowBoard for everything to work fine. As far as I am concerned, Shadow is working as intended since the files from EmojiPort can be detected by apps if app developers are evil enough to do so.

To be honest, I'm not really sure how EmojiPort works and why SnowBoard allows it to work properly with Shadow.

Just to summarize how my tweak compatibility system works, Shadow backtraces each hook call to determine whether or not the hooked method was called by a tweak and bypasses any restrictions. Maybe with SnowBoard EFM enabled it causes the new emojis to be loaded via tweak rather than natively through the system?

cc: @PoomSmart

**Comment by PoomSmart** [comment] 2023-01-29 05:45
EmojiFontManager automatically converts existing EFM fonts into SnowBoard-compatible. I'm not sure if this is the case for rootless jailbreaks like XinaA15 though. I didn't test it on that yet.

**Comment by PoomSmart** [comment] 2023-01-29 05:48
I will test the things later today and see what sort of issues come up.

**Comment by PoomSmart** [comment] 2023-01-29 05:52
@nk950357 Which apps you are having issues with?

**Comment by nk950357** [comment] 2023-01-29 05:52
> Those instructions seem out of date. Maybe it comes from an old (old old old) version of EmojiPort? Like before EFM even exists or something?
> 
> 
> 
> I have the latest packages of everything for EmojiPort and EFM, and all I have to do is enable EFM in SnowBoard for everything to work fine. As far as I am concerned, Shadow is working as intended since the files from EmojiPort can be detected by apps if app developers are evil enough to do so.
> 
> 
> 
> To be honest, I'm not really sure how EmojiPort works and why SnowBoard allows it to work properly with Shadow.
> 
> 
> 
> Just to summarize how my tweak compatibility system works, Shadow backtraces each hook call to determine whether or not the hooked method was called by a tweak and bypasses any restrictions. Maybe with SnowBoard EFM enabled it causes the new emojis to be loaded via tweak rather than natively through the system?
> 
> 
> 
> cc: @PoomSmart

I'm pretty sure the instructions I follow isn't old, because two months ago the snowboard way in instructions isn't deprecated. 

I updated to the latest version last week and found out that using snowboard causing part of new emoji not work, and found out that the snowboard has been deprecated. By disabling snowboard works well for latest version but causing all emoji gone problem like the OP.

**Comment by PoomSmart** [comment] 2023-01-29 05:53
As for Emoji fonts support for SnowBoard, I might instead have a script to convert EFM fonts to be recognizable by SnowBoard somehow.

**Comment by nk950357** [comment] 2023-01-29 05:55
> @nk950357 Which apps you are having issues with?

Line.
https://apps.apple.com/tw/app/line/id443904275?l=en
Not sure if US can download it or not.

**Comment by nk950357** [comment] 2023-01-29 05:58
FYI, I’m using Taurine with iOS 14.3.

**Comment by PoomSmart** [comment] 2023-01-29 06:10
So, just LINE app?

**Comment by nk950357** [comment] 2023-01-29 06:17
> So, just LINE app?

Right now I only found line has this problem.

I've tested another app "Line Pay", if I disable snowboard for it will causing emoji not showing but barmoji works, a little bit different situation with the line app.![image](https://user-images.githubusercontent.com/51433626/215308662-90a81dce-f190-4ef9-8aba-330f59acd63b.png)

FYI, only enabling shadow's "Low-level File Handles" bypass has snowboard problem.

**Comment by jjolano** [comment] 2023-01-29 06:28
The relevant code for this particular hook is here: https://github.com/jjolano/shadow/blob/5b2b590375025213da026164f678feabcdbb9f4e/Shadow.dylib/hooks/libc.x#L712-L778

Simple reimplementation of the functions, no different restriction from any other hook.

The `isCallerTweak` method is what allows tweaks to bypass the restriction, as is the case with SnowBoard + EFM enabled. The strange thing is, even trying by excluding **all** EmojiPort-related paths (so that `isCPathRestricted` returns FALSE), it still doesn't work without SnowBoard. But maybe I'm missing something or my hook implementation is wrong.

**Comment by PoomSmart** [comment] 2023-01-29 11:22
Unable to reproduce the issue on iPadOS 14.3, Taurine 1.1.6, LINE 13.0.1, Shadow (beta) tweak 3.6.2-3+debug, SnowBoard 1.5.1~Beta1, SnowBoard Fonts Extension 1.0.12~Beta4.

**Comment by nk950357** [comment] 2023-01-29 11:25
> Unable to reproduce the issue on iPadOS 14.3, Taurine 1.1.6, LINE 13.0.1, Shadow (beta) tweak 3.6.2-3+debug, SnowBoard 1.5.1-Beta1, SnowBoard Fonts Extension 1.0.12-Beta4.

If I use emojiport with snowboard is okay, with EFM only then it won't work.

**Comment by PoomSmart** [comment] 2023-01-29 11:28
I see, part of the logs also say:

![Uploading image.png…]()

cc @jjolano

**Comment by PoomSmart** [comment] 2023-01-29 11:29
I see, part of the logs also say:

`isPathCompliant: path '/Library/Themes/EmojiFontManager/NotoColorEmoji.font/AppleColorEmoji@2x.ttc' not compliant (key: /Library)`

cc @jjolano

**Comment by jjolano** [comment] 2023-01-29 18:03
> I see, part of the logs also say:
> 
> ```
> isPathCompliant: path '/Library/Themes/EmojiFontManager/NotoColorEmoji.font/AppleColorEmoji@2x.ttc' not compliant (key: /Library)
> isPathRestricted: restricted: /Library/Themes/EmojiFontManager/NotoColorEmoji.font/AppleColorEmoji@2x.ttc
> ```
> 
> cc @jjolano

Interesting. What function accesses this file? Seems I may need to try and hook it to apply `isCallerTweak`.

**Comment by jjolano** [comment] 2023-01-29 18:09
I have updated the beta with more adjustments. See if this makes any difference.

**Comment by nk950357** [comment] 2023-01-30 14:36
The previous beta version fails to bypass the line app  jb detection with same hook function but the latest stable version works well. Not sure if some beta update with my problem breaks the bypass.

**Comment by jjolano** [comment] 2023-01-30 20:02
I think I figured out a good fix for this. Although I'm unsure if it affects detection as the changes are directly on `isCallerTweak`. See if the latest beta works for both non-SnowBoard and with SnowBoard.

**Comment by PoomSmart** [comment] 2023-01-31 01:17
Yep, it's working now.

**Comment by nk950357** [comment] 2023-01-31 02:00
> I think I figured out a good fix for this. Although I'm unsure if it affects detection as the changes are directly on `isCallerTweak`. See if the latest beta works for both non-SnowBoard and with SnowBoard. This adjustment happens to fix a lot of other tweak-related things aside from emojis.
> 
> 
> 
> No longer requires `Allow Tweak Resources`.

Can confirm that doesn't need snowboard now!
But same with the 3.6.2 beta4, bypass doesn't work.

**Comment by jjolano** [comment] 2023-01-31 05:17
Good to know its working. Are you saying beta 3 works and since beta 4 the bypass is not working?

**Comment by nk950357** [comment] 2023-02-01 00:42
> Good to know its working. Are you saying beta 3 works and since beta 4 the bypass is not working?

I haven't tried beta version before, only tried 3.6.2b4 to test the compatibility of line and emojiport.
What I can confirm is 3.6.1 works.
Now I can't found the 3.6.2b1-b3's download link, could you provide me the deb packages so that I can test them? Thanks.

**Comment by jjolano** [comment] 2023-02-01 01:41
> > Good to know its working. Are you saying beta 3 works and since beta 4 the bypass is not working?
> 
> I haven't tried beta version before, only tried 3.6.2b4 to test the compatibility of line and emojiport.
> What I can confirm is 3.6.1 works.
> Now I can't found the 3.6.2b1-b3's download link, could you provide me the deb packages so that I can test them? Thanks.

Please try the latest beta. I made another small adjustment. I will also double check some changes from 3.6.1.

Also, is there another app where detection has been affected?

**Closed** 2023-02-02 15:39 UTC

**Comment by nk950357** [comment] 2023-02-02 15:52
> Since the original issue is resolved, I'll close this. Please create a new issue if there is a regression from 3.6.1.

Sorry for the late reply. Only line has the bypass problem in latest beta, b12 still no works.
Does it mean i need to create a new issue about this situation right?

**Comment by jjolano** [comment] 2023-02-02 17:46
Yes, please create a new issue with a list of options enabled and things you tried.

**Comment by nk950357** [comment] 2023-02-03 09:07
> Yes, please create a new issue with a list of options enabled and things you tried.

Sorry for wrong report. Tried enable Enhance Path Processing works now. Thanks!
